apiVersion: apps/v1
kind: Deployment
metadata:
  name: mw-backend
  labels:
    app: mw-backend
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: mw-backend
  template:
    metadata:
      labels:
        app: mw-backend
    spec:
      containers:
        - name: backend
          image: quay.io/eksta_mannen/backend-argo:ab4c203c4390e35ae4aa9067e2791594d50c49e1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          # Miljövariabler för att hitta databaserna
          env:
            # Postgres-konfiguration
            - name: DB_HOST
              value: "mw-postgres-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mw-guestbook-secrets
                  key: database-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mw-guestbook-secrets
                  key: database-password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mw-guestbook-secrets
                  key: database-name
            # Redis-konfiguration
            - name: REDIS_HOST
              value: "mw-redis-service"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mw-guestbook-secrets
                  key: redis-password
            # App-konfiguration
            - name: PORT
              value: "8080"
          # Readiness Probe (Kollar /health endpointen)
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          # Liveness Probe (Startar om den om den dör helt)
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
