apiVersion: apps/v1
kind: Deployment
metadata:
  name: mw-postgres-debug
  labels:
    app: mw-postgres-debug
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: mw-postgres-debug
  template:
    metadata:
      labels:
        app: mw-postgres-debug
    spec:
      terminationGracePeriodSeconds: 0 # Snabbare omstart vid debug
      containers:
        - name: postgres-debug
          image: quay.io/eksta_mannen/postgres-argo:latest
          imagePullPolicy: Always
          # HÄR ÄR DEBUG-TRICKET:
          command: ["sleep"]
          args: ["infinity"]
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: mw-guestbook-secrets
                  key: database-user
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mw-guestbook-secrets
                  key: database-password
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mw-guestbook-secrets
                  key: database-name
          resources:
            requests:
              memory: "256Mi"
              cpu: "50m"
            limits:
              memory: "512Mi"
              cpu: "250m"
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/pgsql/data
      volumes:
        - name: pg-data
          persistentVolumeClaim:
            claimName: mw-postgres-pvc