apiVersion: v1
kind: Service
metadata:
  name: mw-postgres-service # Detta namn används som "hostname" av din backend
spec:
  selector:
    app: mw-postgres # Måste matcha labeln i din Deployment
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432