apiVersion: apps/v1
kind: Deployment
metadata:
  name: mw-redis-deployment
  labels:
    app: mw-redis
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: mw-redis
  template:
    metadata:
      labels:
        app: mw-redis
    spec:
      containers:
        - name: redis
          image: quay.io/eksta_mannen/redis-argo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
            
          # TILLFÄLLIGT LÖSENORD FÖR TEST
          env:
            - name: REDIS_PASSWORD
              value: "testpass"

          # Denna kommer nu använda "testpass" automatiskt
          readinessProbe:
            exec:
              command: ["sh", "-c", "redis-cli -a $REDIS_PASSWORD ping"]
            initialDelaySeconds: 5
            periodSeconds: 10
            
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
              
          volumeMounts:
            - name: redis-data
              mountPath: /var/lib/redis/data
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: mw-redis-pvc